# Generated by Django 2.2.5 on 2019-10-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='category',
            field=models.TextField(default='course category'),
        ),
        migrations.AddField(
            model_name='lectures',
            name='udemy_completion_ratio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lectures',
            name='udemy_course_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lectures',
            name='udemy_course_title',
            field=models.TextField(default='course title'),
        ),
        migrations.AddField(
            model_name='lectures',
            name='udemy_name',
            field=models.TextField(default='this is my udemy name'),
        ),
        migrations.AddField(
            model_name='lectures',
            name='udemy_number_subscribed_courses',
            field=models.TextField(default=' this is the number of courses i have'),
        ),
    ]
