# Generated by Django 2.2.5 on 2019-10-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_auto_20191004_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='udemy_course_instructor',
            field=models.TextField(default='UKNOWN'),
        ),
        migrations.AddField(
            model_name='lectures',
            name='udemy_course_price',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='lectures',
            name='udemy_course_url',
            field=models.TextField(default='UKNOWN'),
        ),
        migrations.AlterField(
            model_name='lectures',
            name='udemy_name',
            field=models.TextField(default='falbellaihi'),
        ),
        migrations.AlterField(
            model_name='lectures',
            name='udemy_number_subscribed_courses',
            field=models.TextField(default='until i figure a way to get it, this is default value'),
        ),
    ]
