# Generated by Django 2.2.5 on 2019-10-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtube',
            name='title',
        ),
        migrations.AddField(
            model_name='youtube',
            name='yotube_video_id',
            field=models.TextField(default='id'),
        ),
        migrations.AddField(
            model_name='youtube',
            name='youtube_video_thum_url',
            field=models.TextField(default='thum url'),
        ),
        migrations.AddField(
            model_name='youtube',
            name='youtube_video_title',
            field=models.CharField(default='title', max_length=300),
        ),
        migrations.AddField(
            model_name='youtube',
            name='youtube_video_url',
            field=models.TextField(default='url'),
        ),
    ]
