# Generated by Django 2.2.5 on 2019-10-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_auto_20191004_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='yotube_video_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='youtube',
            name='youtube_minuts_watched',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='youtube',
            name='youtube_video_description',
            field=models.TextField(default='UNKNWN'),
        ),
    ]
