# Generated by Django 2.2.5 on 2019-10-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0006_auto_20191004_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='udemy_course_thum',
            field=models.TextField(default='thum url'),
        ),
    ]
