# Generated by Django 2.2.5 on 2019-10-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0007_lectures_udemy_course_thum'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='youtube_percentage_completed',
            field=models.IntegerField(default=0),
        ),
    ]
